# This Flask app requires a Python runtime and is not suitable for Netlify
# Please deploy to a platform that supports Python web applications like:
# - Render (render.com)
# - Railway (railway.app) 
# - Heroku (heroku.com)
# - DigitalOcean App Platform

# For static file hosting only (if you want to host just the frontend):
[build]
  publish = "static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200