services:
  - type: web
    name: github-issue-cost-estimator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
    # Add your environment variables here:
    # - key: ANTHROPIC_API_KEY
    #   sync: false
    # - key: OPENAI_API_KEY  
    #   sync: false
    # - key: GITHUB_TOKEN
    #   sync: false
    # - key: LLM_PROVIDER
    #   value: anthropic